version: '3.8'

services:
  task-runner:
    image: m3u2strm:latest
    environment:
      - TASK_INTERVAL=30
      - M3U_URL=http://example.com/playlist.m3u
      - SERIES_GROUPS=SERIES,DIZILER
      - MOVIES_GROUPS=MOVIES,FILMLER
      - LIVE_GROUPS=LIVE,TV,ULUSAL
      - TELEGRAM_BOT_TOKEN=your_bot_token
      - TELEGRAM_CHAT_ID=your_chat_id
      - DEBUG_LOGGING=false
      - WEB_UI_PORT=8475 
    ports:
      - "8475:8475"
    volumes:
      - ./data:/app/vods
    restart: unless-stopped
